apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: octopus-homolog
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu:18.04
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always