---
apiVersion: v1
kind: Service
metadata:
  name: octopus-fila-service
  namespace: octopus-homolog
  labels:
    app: octopus-fila
spec:
  #externalName: octopus-fila-service.octopus-homolog.svc.cluster.local
  #type: ExternalName
  selector:
    app: octopus-fila
  ports:
  - name: dashboard
    port: 8162
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61617
    targetPort: 61616
    protocol: TCP
#  - name: amqp
#    port: 5672
#    targetPort: 5672
#    protocol: TCP
  - name: stomp
    port: 61613
    targetPort: 61613
    protocol: TCP
#  - name: mqtt
#    port: 1883
#    targetPort: 1883
#    protocol: TCP
  type: ClusterIP
