---
apiVersion: v1
kind: Namespace
metadata:
  name: octopus-homolog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-fila-pvc
  namespace: octopus-homolog
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-fila
  namespace: octopus-homolog
  labels:
    app: octopus-fila
spec:
  replicas: 1
#    type: Recreate
  selector:
    matchLabels:
      app: octopus-fila
  template:
    metadata:
      labels:
        app: octopus-fila
    spec:
      containers:
      - image: webcenter/activemq
        name: octopus-fila
        imagePullPolicy: Always
        ports:
        - containerPort: 61616
          name: jmx
          protocol: TCP
        - containerPort: 8161
          name: ui
          protocol: TCP
        - containerPort: 61616
          name: openwire
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 61613
          name: stomp
          protocol: TCP
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        env:
        - name: ACTIVEMQ_ENABLED_AUTH
          value: "false"
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: admin
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: admin
        - name: ACTIVEMQ_ENABLED_SCHEDULER
          value: "true"
        - name: ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT
          value: "true"
        resources:
          requests:
            cpu: "1024m"
            memory: "1024Mi"
          limits:
            cpu: "1024m"
            memory: "2048Mi"

        volumeMounts:
        - name: octopus-fila-volume
          mountPath: /data/activemq

      volumes:
      - name: octopus-fila-volume
        persistentVolumeClaim:
          claimName: octopus-fila-pvc
