---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-fila-pvc
  namespace: octopus-homolog
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
