apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-db-pvc
  namespace: octopus-homolog
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
