apiVersion: v1
kind: Service
metadata:
  name: octopus-db-service
  labels:
    app: octopus-db
    namespace: octopus-homolog
spec:
  ports:
    - port: 5432
  selector:
    app: octopus-db
  type: ClusterIP
