---
apiVersion: v1
kind: Service
metadata:
  name: octopus-db-service
  namespace: octopus-homolog
  labels:
    app: octopus-db
spec:
        #externalName: octopus-db-service.octopus-homolog.svc.cluster.local
  #type: ExternalName
  ports:
    - port: 5432
  selector:
    app: octopus-db
  type: ClusterIP
