---
apiVersion: v1
kind: Namespace
metadata:
  name: octopus-homolog

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-db-pvc
  namespace: octopus-homolog
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-db
  namespace: octopus-homolog
  labels:
    app: octopus-db
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: octopus-db
  template:
    metadata:
      labels:
        app: octopus-db
    spec:
      containers:
      - image: postgres:12-alpine
        name: octopus-db
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: octopus
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: octopus-db
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "4096Mi"

        volumeMounts:
        - name: octopus-db-volume
          mountPath: /var/lib/postgresql/data

#        env:
#        - name: POSTGRES_PASSWORD
#          value: XXXXXXX
#        - name: POSTGRES_DB
#          value: XXXXXXX
#        - name: PGDATA
#          value: /var/lib/postgresql/data/pgdata

      volumes:
      - name: octopus-db-volume
        persistentVolumeClaim:
          claimName: octopus-db-pvc
